### ISSUE TITLE
Error in uploading workflow

### ISSUE THREAD

**Issue by VGPReys** [i-VRESSE/workflow-builder#150]
Got the following error(s) while trying to upload a workflow in workflow builder (http://localhost:8080/builder):

Workflow archive failed to load.
- Error in nodes[0]: must have node name belonging to known nodes
- Error in nodes[5]: must NOT have additional properties: tolerance
- Error in nodes[7]: must NOT have additional properties: tolerance

here is the `workflow.cfg` file content:

```toml
# ====================================================================
# Antibody-antigen docking example with restraints from the antibody
# paratope to the NMR-identified epitope on the antigen 
# ====================================================================

# directory in which the scoring will be done
run_dir = "run1-CDR-NMR-CSP"

# compute mode
mode = "local"
ncores = 50

# Self contained rundir (to avoid problems with long filename paths)
self_contained = true

# Post-processing to generate statistics and plots
postprocess = true
clean = true

molecules =  [
    "4G6K_clean.pdb",
    "4I1B_clean.pdb"
    ]

# ====================================================================
# Parameters for each stage are defined below, prefer full paths
# ====================================================================
[topoaa]

[rigidbody]
# CDR to NMR epitope ambig restraints
ambig_fname = "ambig-paratope-NMR-epitope.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"
sampling = 50

[caprieval]
reference_fname = "4G6M_matched.pdb"

[seletop]
# Selection of the top 40 best scoring complexes
select = 40

[flexref]
tolerance = 5
# CDR to NMR epitope ambig restraints
ambig_fname = "ambig-paratope-NMR-epitope.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"

[caprieval]
reference_fname = "4G6M_matched.pdb"

[emref]
tolerance = 5
# CDR to NMR epitope ambig restraints
ambig_fname = "ambig-paratope-NMR-epitope.tbl"
# Restraints to keep the antibody chains together
unambig_fname = "antibody-unambig.tbl"

[caprieval]
reference_fname = "4G6M_matched.pdb"

[clustfcc]
plot_matrix = true

[seletopclusts]
# Selection of the top 4 best scoring complexes from each cluster
top_models = 4

[caprieval]
reference_fname = "4G6M_matched.pdb"

[contactmap]

# ====================================================================

```
