### ISSUE TITLE
Expandable parameters

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#47]
Haddock3 has parameters with numbers in their name. See https://github.com/haddocking/haddock3/blob/e324b9cbd4c9c76ea1df6ce874e8ba5317486218/src/haddock/gear/expandable_parameters.py#L1-L47 for a description.

Refs https://github.com/haddocking/haddock3/issues/337 and https://github.com/haddocking/haddock3/issues/339

# Idea

Below is an idea how the expandable parameters can be mapped to the builder

To remain generic the expandable parameters can be mapped to a JSON schema equivalent together with a configuration that tells the builder how to read/write the toml with the correct indexes.

There are 3 types defined

# Array of scalars

In toml

```toml
param_1 = 11
param_2 = 22
param_3 = 33
```

In catalog

```yaml
schema:
  type: object
  properties:
    param:
      type: array
      items:
        type: number
tomlSchema:
  param:
    indexed: true
```

In memory

```json
{
  "param": [11,22,33]
}
```

# Array of objects

In toml

```toml
name_something_1 = 11
name_something_else_1 = 22
name_something_2 = 33
name_something_else_2 = 44
```

In catalog

```yaml
schema:
  type: object
  properties:
    name:
      type: array
      items:
        type: object
        properties:
          something:
            type: number
          something_else:
            type: number
tomlSchema:
  name:
    indexed: true
    items:
      flatten: true
```

In memory

```json
{
  "name": [{
    "something": 11,
    "something_else": 22,
  }, {
    "something": 33,
    "something_else": 44,
  }]
}
```

# Array of array of objects

In toml

```toml
fle_sta_1_1 = 11
fle_end_1_1 = 22
fle_sta_1_2 = 33
fle_end_1_2 = 44
fle_sta_2_1 = 55
fle_end_2_1 = 66
```

In catalog

```yaml
schema:
  type: object
  additionalProperties: false
  properties:
    fle:
      type: array
      description: Outer array is molecule index
      items:
        type: array
        description: Inner array is segment index
        items:
          type: object
          properties:
            sta:
              title: Starting residue number
              type: number
            end:
              title: End residue number
              type: number
          additionalProperties: false
tomlSchema:
  fle:
    indexed: true
    items:
      indexed: true
      items:
        flatten: true
```

In memory

```json
{
    "fle": [
        [
            {
                "sta": 11,
                "end": 22
            },
            {
                "sta": 33,
                "end": 44
            }
        ],
        [
            {
                "sta": 55,
                "end": 66
            }
        ]
    ]
}
```

**Comment by sverhoeven** [comment]
MolX in topoaa is another type

## Array of objects with object as toml table

In toml

```toml
[topoaa.mol1]
cyclicpept = false

[topoaa.mol2]
cyclicpept = true
```

In catalog

```yaml
schema:
  type: object
  properties:
    mol:
      type: array
      items:
        type: object
        properties:
          cyclicpept:
            type: boolean
tomlSchema:
  mol:
    indexed: true
    items:
      sectioned: true
```

In memory

```json
{
  "mol": [{
    "cyclicpept": false
  }, {
    "cyclicpept": true
  }]
}
```
