### ISSUE TITLE
Checkbox widget does not render description

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#61]
![localhost_3000_ (4)](https://user-images.githubusercontent.com/1713488/161565755-fe027bb8-be5d-4e83-b023-74d617ab6264.png)
while in catalog the parameter looks like

```yaml
      mol_fix_origin:
        type: array
        items:
          default: false
          title: Fix molecule
          description: Fixes the molecule in its original position.
          $comment: Fixes the molecule in its original position.
          type: boolean
```

I expected the ` Fixes the molecule in its original position.` to be shown near the checkbox..
