### ISSUE TITLE
Make resdic_ parameter molecule aware

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/workflow-builder#88]
Continuation of #77

The build since #87 can output 

```toml
param_A = [11]
param_B = [22]
param_C = [33]
```

However when molecules are uploaded the chain and residue numbers can be filtered, see #77 .
